version: '3'

services:
  rancher:
    image: rancher/rancher:v2.0.2
    container_name: rancher
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/rancher:/var/lib/rancher:Z
